---
version: "3"
services:
    impf-botpy:
        build: .
        volumes:
            - ./settings.py:/app/settings.py
        ports:
            - 5901:5901
            - 6901:6901
        tmpfs: /tmp
        environment:
            - TZ=Europe/Berlin
            - VNC_PASSWORD=CHANGEME
        restart: unless-stopped
